version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3

  - package-ecosystem: "npm-and-yarn"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
