export const METRIC_MAPS = {
  attackVector: { N: 'Network', A: 'Adjacent Network', L: 'Local', P: 'Physical' },
  attackComplexity: { L: 'Low', H: 'High' },
  privilegesRequired: { N: 'None', L: 'Low', H: 'High' },
  userInteraction: { N: 'None', R: 'Required' },
  scope: { U: 'Unchanged', C: 'Changed' },
  confidentialityImpact: { N: 'None', L: 'Low', H: 'High' },
  integrityImpact: { N: 'None', L: 'Low', H: 'High' },
  availabilityImpact: { N: 'None', L: 'Low', H: 'High' },
  exploitCodeMaturity: { X: 'Not Defined', H: 'High', F: 'Functional', P: 'Proof-of-Concept', U: 'Unproven' },
  remediationLevel: { X: 'Not Defined', O: 'Official Fix', T: 'Temporary Fix', W: 'Workaround', U: 'Unavailable' },
  reportConfidence: { X: 'Not Defined', C: 'Confirmed', R: 'Reasonable', U: 'Unknown' },
  modifiedAttackVector: { X: 'Not Defined', N: 'Network', A: 'Adjacent Network', L: 'Local', P: 'Physical' },
  modifiedAttackComplexity: { X: 'Not Defined', L: 'Low', H: 'High' },
  modifiedPrivilegesRequired: { X: 'Not Defined', N: 'None', L: 'Low', H: 'High' },
  modifiedUserInteraction: { X: 'Not Defined', N: 'None', R: 'Required' },
  modifiedScope: { X: 'Not Defined', U: 'Unchanged', C: 'Changed' },
  modifiedConfidentialityImpact: { X: 'Not Defined', N: 'None', L: 'Low', H: 'High' },
  modifiedIntegrityImpact: { X: 'Not Defined', N: 'None', L: 'Low', H: 'High' },
  modifiedAvailabilityImpact: { X: 'Not Defined', N: 'None', L: 'Low', H: 'High' },
  confidentialityRequirement: { X: 'Not Defined', L: 'Low', M: 'Medium', H: 'High' },
  integrityRequirement: { X: 'Not Defined', L: 'Low', M: 'Medium', H: 'High' },
  availabilityRequirement: { X: 'Not Defined', L: 'Low', M: 'Medium', H: 'High' },
};
