import json
import logging
from typing import Any

from pydantic import BaseModel, Field
from sqlalchemy.ext.asyncio import AsyncSession

from app.features.llm_templates.models.llm_template_models import AITemplate
from app.features.llm_templates.schemas.llm_template_schemas import AITemplateExecute
from app.features.llm_templates.utils.web_content_fetcher import fetch_web_contexts, format_web_contexts_for_prompt
from app.utils.llm_service import build_model_registry, execute_prompt, execute_structured_prompt, get_default_model_id

logger = logging.getLogger(__name__)


def parse_json_field(field_data: Any, field_name: str) -> list[dict[str, Any]]:
    """Parse a JSON string field into a list, raising ValueError on malformed input"""
    if isinstance(field_data, str):
        try:
            return json.loads(field_data)
        except (json.JSONDecodeError, TypeError) as e:
            logger.error("Failed to parse %s: %s", field_name, e)
            raise ValueError(f"Template {field_name} contains invalid JSON")
    return field_data or []


def validate_required_payload_fields(
    payload_fields: list[dict[str, Any]],
    provided_data: dict[str, str],
) -> None:
    """Raise ValueError if any required payload fields are missing from provided_data"""
    required_fields = {field["name"] for field in payload_fields if field.get("required", False)}
    missing = required_fields - set(provided_data.keys())
    if missing:
        logger.warning("Missing required payload fields: %s", missing)
        raise ValueError(f"Missing required payload fields: {', '.join(missing)}")


def build_template_prompt(
    template: AITemplate,
    payload_data: dict[str, str],
    web_content: str = "",
    static_content: str = "",
) -> str:
    """Build the complete prompt by substituting payload data into the template task"""
    formatted_prompt = template.ai_agent_task

    for name, value in payload_data.items():
        tag_open = f"<{name}>"
        tag_close = f"</{name}>"
        if tag_open in formatted_prompt:
            formatted_prompt = formatted_prompt.replace(tag_open, str(value)).replace(tag_close, "")
        else:
            formatted_prompt += f"\n\n{tag_open}\n{value}\n{tag_close}"

    if static_content:
        formatted_prompt += f"\n\n# Static Context\n\n{static_content}"

    if web_content:
        formatted_prompt += f"\n\n# Web Context\n\n{web_content}"

    return formatted_prompt


def format_static_contexts(static_contexts: list[dict[str, Any]]) -> str:
    """Format a list of static context dicts into a markdown-style string for prompt inclusion"""
    if not static_contexts:
        return ""

    content_parts = []
    for context in static_contexts:
        name = context.get("name", "Context")
        content = context.get("content", "")
        description = context.get("description", "")

        context_part = f"## {name}"
        if description:
            context_part += f"\n{description}"
        context_part += f"\n\n{content}"
        content_parts.append(context_part)

    return "\n\n---\n\n".join(content_parts)


async def process_web_contexts(web_contexts: list[dict[str, Any]]) -> str:
    """Fetch and format web contexts, returning an empty string on failure"""
    if not web_contexts:
        return ""

    try:
        logger.debug("Fetching %d web contexts", len(web_contexts))
        fetched_contexts = await fetch_web_contexts(web_contexts)
        return format_web_contexts_for_prompt(fetched_contexts)
    except Exception as e:
        logger.warning("Failed to fetch web contexts: %s", e)
        return f"<!-- Warning: Failed to fetch web contexts: {e} -->"


def prepare_template_execution_data(
    template: AITemplate,
    execution_data: AITemplateExecute,
) -> dict[str, Any]:
    """Parse and validate template fields, returning a unified execution config dict"""
    payload_fields = parse_json_field(template.payload_fields, "payload_fields")
    validate_required_payload_fields(payload_fields, execution_data.payload_data)

    web_contexts = parse_json_field(template.web_contexts, "web_contexts")
    static_contexts = parse_json_field(template.static_contexts, "static_contexts")

    model_id = execution_data.override_model or template.model or ""
    temperature = execution_data.override_temperature
    if temperature is None:
        temperature = template.temperature or 0.7

    return {
        "payload_fields": payload_fields,
        "web_contexts": web_contexts,
        "static_contexts": static_contexts,
        "model_id": model_id,
        "temperature": temperature,
    }


class EngineeredPayloadField(BaseModel):
    """Schema for a payload field generated by prompt engineering."""
    name: str = Field(description="Field name using alphanumeric characters, hyphens, or underscores")
    description: str = Field(description="What this field is for")
    required: bool = Field(description="Whether the field is mandatory")


class EngineeredPrompt(BaseModel):
    """Structured output model for prompt engineering results."""
    ai_agent_role: str = Field(description="A clear, directive AI persona. Use a professional expert tone.")
    ai_agent_task: str = Field(
        description="Detailed step-by-step task instructions. "
        "Use <field_name> tags as placeholders for user payload data."
    )
    payload_fields: list[EngineeredPayloadField] = Field(
        description="Fields the end user must provide when executing the template"
    )
    example_input_output: str = Field(
        description="Markdown-formatted example demonstrating sample input and expected output"
    )


PROMPT_ENGINEER_SYSTEM = (
    "You are a world-class prompt engineer. "
    "Generate a complete, well-organized prompt configuration based on the given title and description."
)


def build_prompt_engineering_prompt(title: str, description: str) -> str:
    """Build the user prompt for the prompt engineering agent"""
    return (
        f"Title: {title}\n"
        f"Description: {description}\n\n"
        "Generate a prompt configuration with:\n"
        "- ai_agent_role: A professional, directive persona for the AI agent.\n"
        "- ai_agent_task: Detailed instructions. Use <field_name> tags as placeholders for user input.\n"
        "- payload_fields: The input fields a user must provide.\n"
        "- example_input_output: A markdown example of sample input and expected output."
    )


async def run_engineer_prompt(title: str, description: str, model_id: str | None, db: AsyncSession) -> dict[str, Any]:
    """Run the prompt-engineering workflow using structured output and return template data"""
    prompt = build_prompt_engineering_prompt(title, description)
    models = await build_model_registry(db)

    if not model_id or model_id not in models:
        model_id = await get_default_model_id(db, "llm_templates")

    result = await execute_structured_prompt(
        models,
        model_id=model_id,
        system_prompt=PROMPT_ENGINEER_SYSTEM,
        user_prompt=prompt,
        output_type=EngineeredPrompt,
        temperature=0.7,
    )

    return result.model_dump()


async def run_execute_template(
    template: AITemplate,
    execution_data: AITemplateExecute,
    db: AsyncSession,
) -> str:
    """Run the full template execution workflow and return the LLM result"""
    execution_config = prepare_template_execution_data(template, execution_data)

    web_content = await process_web_contexts(execution_config["web_contexts"])
    static_content = format_static_contexts(execution_config["static_contexts"])

    formatted_prompt = build_template_prompt(
        template=template,
        payload_data=execution_data.payload_data,
        web_content=web_content,
        static_content=static_content,
    )

    models = await build_model_registry(db)

    model_id = execution_config["model_id"]
    if model_id not in models:
        logger.warning("Model '%s' not available, falling back to configured default", model_id)
        model_id = await get_default_model_id(db, "llm_templates")

    logger.info("Executing template with model: %s, temperature: %s", model_id, execution_config["temperature"])

    return await execute_prompt(
        models,
        model_id=model_id,
        system_prompt=template.ai_agent_role,
        user_prompt=formatted_prompt,
        temperature=execution_config["temperature"],
        max_tokens=1000,
    )
