"""add candidates to ru_business_check_searches

Revision ID: 156f6418a311
Revises: 6f4bb468c85a
Create Date: 2026-08-13 00:43:23.572601

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "156f6418a311"
down_revision: str | None = "6f4bb468c85a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ru_business_check_searches",
        sa.Column(
            "candidates",
            sa.JSON(),
            nullable=True,
            comment=(
                "Brief per-entity info when the query matched multiple ЕГРЮЛ/ЕГРИП rows "
                "(name search) - empty once resolved to a single entity"
            ),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ru_business_check_searches", "candidates")
    # ### end Alembic commands ###
