"""add steam recon searches

Revision ID: 29302d5d0294
Revises: b4d92e6a1c58
Create Date: 2026-09-28 22:13:05.890808

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29302d5d0294"
down_revision: str | None = "b4d92e6a1c58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "steam_recon_searches",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "target",
            sa.String(length=512),
            nullable=False,
            comment="Raw target input (SteamID/URL/vanity) as the user entered it",
        ),
        sa.Column(
            "steamid64",
            sa.String(length=20),
            nullable=True,
            comment="Resolved target SteamID64, once resolution succeeds",
        ),
        sa.Column(
            "persona_name",
            sa.String(length=200),
            nullable=True,
            comment="Target's persona name at scan time",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="running, completed, cancelled, or failed",
        ),
        sa.Column(
            "error_message",
            sa.String(length=1000),
            nullable=True,
            comment="Error detail if status is failed",
        ),
        sa.Column(
            "max_friends",
            sa.Integer(),
            nullable=False,
            comment="Friend cap requested for this scan",
        ),
        sa.Column(
            "include_cs_report",
            sa.Boolean(),
            nullable=False,
            comment="Whether the CS2 cheater-probability report was requested",
        ),
        sa.Column(
            "friends_total",
            sa.Integer(),
            nullable=False,
            comment="Total friends on the target's friend list",
        ),
        sa.Column(
            "friends_analyzed",
            sa.Integer(),
            nullable=False,
            comment="Friends whose own friend list was successfully fetched",
        ),
        sa.Column(
            "friends_located",
            sa.Integer(),
            nullable=False,
            comment="Analyzed friends with a usable location",
        ),
        sa.Column(
            "top_country_code",
            sa.String(length=8),
            nullable=True,
            comment="Leading country hypothesis's ISO code, for the history list",
        ),
        sa.Column(
            "cheater_probability",
            sa.Float(),
            nullable=True,
            comment="CS2 cheater-probability estimate (0-1), when include_cs_report was set",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When the scan started",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the scan finished, if it has",
        ),
        sa.Column(
            "result",
            sa.JSON(),
            nullable=True,
            comment="Full scan result blob: profile, close_friends, geolocation, cheater_report",
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'cancelled', 'failed')",
            name="ck_steam_recon_searches_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_steam_recon_searches_status"), "steam_recon_searches", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_steam_recon_searches_steamid64"),
        "steam_recon_searches",
        ["steamid64"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_steam_recon_searches_steamid64"), table_name="steam_recon_searches")
    op.drop_index(op.f("ix_steam_recon_searches_status"), table_name="steam_recon_searches")
    op.drop_table("steam_recon_searches")
    # ### end Alembic commands ###
