"""add ru_business_check tables

Revision ID: 537d93424e1d
Revises: bf5e06e441df
Create Date: 2026-08-11 21:28:21.732587

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "537d93424e1d"
down_revision: str | None = "bf5e06e441df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ru_business_check_searches",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "query",
            sa.String(length=500),
            nullable=False,
            comment="Raw user input - ИНН or company/IP name",
        ),
        sa.Column(
            "resolved_inn",
            sa.String(length=12),
            nullable=True,
            comment="Resolved ИНН, once the ЕГРЮЛ lookup matches a single entity",
        ),
        sa.Column(
            "entity_type",
            sa.String(length=30),
            nullable=True,
            comment="'legal_entity' or 'individual_entrepreneur', once resolved",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="running, completed, cancelled, or failed",
        ),
        sa.Column("error", sa.Text(), nullable=True, comment="Error detail if status is failed"),
        sa.Column(
            "searched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When the scan started",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the scan reached a terminal state - the report's 'as of' date",
        ),
        sa.Column(
            "egrul_data",
            sa.JSON(),
            nullable=True,
            comment=(
                "Parsed ЕГРЮЛ/ЕГРИП fields (name, address, director, founders, ОКВЭД, "
                "capital, registry status)"
            ),
        ),
        sa.Column(
            "egrul_raw",
            sa.Text(),
            nullable=True,
            comment=(
                "Verbatim ЕГРЮЛ payload (search-result JSON + extracted PDF text) as "
                "received from egrul.nalog.ru"
            ),
        ),
        sa.Column(
            "disqualification_result",
            sa.JSON(),
            nullable=True,
            comment="РДЛ check result: {checked, matched, requires_manual_review, matches: [...]}",
        ),
        sa.Column(
            "disqualification_raw",
            sa.Text(),
            nullable=True,
            comment="Verbatim РДЛ payload as received from service.nalog.ru/disqualified.do",
        ),
        sa.Column(
            "flags",
            sa.JSON(),
            nullable=True,
            comment="List of {code, severity, title, detail} risk flags",
        ),
        sa.Column(
            "risk_level",
            sa.String(length=10),
            nullable=True,
            comment=(
                "low, medium, or high - based only on checked_sources, never implies "
                "full-methodology coverage"
            ),
        ),
        sa.Column(
            "checked_sources",
            sa.JSON(),
            nullable=True,
            comment="Source keys actually queried this scan, snapshotted at scan time",
        ),
        sa.Column(
            "pending_sources",
            sa.JSON(),
            nullable=True,
            comment="Source keys not yet available this stage, snapshotted at scan time",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ru_business_check_searches_resolved_inn"),
        "ru_business_check_searches",
        ["resolved_inn"],
        unique=False,
    )
    op.create_table(
        "ru_business_check_settings",
        sa.Column("id", sa.Integer(), nullable=False, comment="Singleton row id, always 1"),
        sa.Column(
            "fresh_registration_threshold_days",
            sa.Integer(),
            nullable=False,
            comment="Registration age below which the soft 'fresh registration' flag fires",
        ),
        sa.Column(
            "history_retention_days",
            sa.Integer(),
            nullable=False,
            comment=(
                "Days a search (including its raw scraped payloads) is kept before "
                "automatic deletion; 0 = unlimited"
            ),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ru_business_check_settings")
    op.drop_index(
        op.f("ix_ru_business_check_searches_resolved_inn"), table_name="ru_business_check_searches"
    )
    op.drop_table("ru_business_check_searches")
    # ### end Alembic commands ###
