"""add instagram searches table

Revision ID: 5ea952ba68b5
Revises: 29302d5d0294
Create Date: 2026-09-29 00:47:11.861011

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ea952ba68b5"
down_revision: str | None = "29302d5d0294"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instagram_searches",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "scan_type",
            sa.String(length=20),
            nullable=False,
            comment="'followers', 'followees', or 'posts'",
        ),
        sa.Column(
            "username",
            sa.String(length=60),
            nullable=False,
            comment="Instagram username that was scanned",
        ),
        sa.Column(
            "mode",
            sa.String(length=20),
            nullable=False,
            comment="'anonymous' or 'session' - which one the scan actually ran as",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="running, completed, cancelled, or failed",
        ),
        sa.Column("error", sa.Text(), nullable=True, comment="Error detail if status is failed"),
        sa.Column(
            "item_count",
            sa.Integer(),
            nullable=False,
            comment="Items actually collected before stopping",
        ),
        sa.Column(
            "total_count",
            sa.Integer(),
            nullable=True,
            comment="Instagram-reported total count, when the API exposed one",
        ),
        sa.Column(
            "truncated",
            sa.Boolean(),
            nullable=False,
            comment="Hit the per-scan item cap or wall-clock deadline before exhausting the list",
        ),
        sa.Column(
            "searched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When the scan ran",
        ),
        sa.Column(
            "result",
            sa.JSON(),
            nullable=True,
            comment=(
                "Full items list blob (shape depends on scan_type) - no normalized child "
                "table, same pattern as GitReconSearch.result"
            ),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'cancelled', 'failed')",
            name="ck_instagram_searches_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_instagram_searches_username"), "instagram_searches", ["username"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_instagram_searches_username"), table_name="instagram_searches")
    op.drop_table("instagram_searches")
    # ### end Alembic commands ###
