"""add arbitration fields to ru_business_check

Revision ID: 6f4bb468c85a
Revises: de923d7047e4
Create Date: 2026-08-12 03:01:15.874543

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f4bb468c85a"
down_revision: str | None = "de923d7047e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ru_business_check_searches",
        sa.Column(
            "arbitration_data",
            sa.JSON(),
            nullable=True,
            comment=(
                "Arbitration case list: {checked, cases: [{case_number, "
                "date_registered, role, status, court, claim_amount, case_url}]}"
            ),
        ),
    )
    op.add_column(
        "ru_business_check_searches",
        sa.Column(
            "arbitration_raw",
            sa.Text(),
            nullable=True,
            comment="Verbatim arbitration search-result payload as received from kad.arbitr.ru",
        ),
    )
    # server_default backfills existing rows (this table's a pre-existing singleton once
    # anyone has opened RU Business Check settings or run a scan) - autogenerate only
    # emits the ORM-side Python default, which SQLite's ALTER TABLE ADD COLUMN ... NOT
    # NULL rejects outright without a server-side value to backfill with.
    op.add_column(
        "ru_business_check_settings",
        sa.Column(
            "small_claim_amount_threshold",
            sa.Integer(),
            nullable=False,
            server_default="100000",
            comment=(
                "Claim amount (RUB) below which a single resolved arbitration case as "
                "defendant is a soft flag"
            ),
        ),
    )
    op.add_column(
        "ru_business_check_settings",
        sa.Column(
            "large_claim_amount_threshold",
            sa.Integer(),
            nullable=False,
            server_default="1000000",
            comment=(
                "Claim amount (RUB) above which any arbitration case as defendant "
                "triggers the 'significant claims' soft flag"
            ),
        ),
    )
    op.add_column(
        "ru_business_check_settings",
        sa.Column(
            "multiple_claims_defendant_threshold",
            sa.Integer(),
            nullable=False,
            server_default="3",
            comment=(
                "Number of arbitration cases as defendant at/above which the 'multiple "
                "claims' soft flag fires"
            ),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ru_business_check_settings", "multiple_claims_defendant_threshold")
    op.drop_column("ru_business_check_settings", "large_claim_amount_threshold")
    op.drop_column("ru_business_check_settings", "small_claim_amount_threshold")
    op.drop_column("ru_business_check_searches", "arbitration_raw")
    op.drop_column("ru_business_check_searches", "arbitration_data")
    # ### end Alembic commands ###
