"""add amass searches table

Revision ID: 6f94ea21edb9
Revises: ca2b89247773
Create Date: 2026-09-11 14:16:38.206236

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f94ea21edb9"
down_revision: str | None = "ca2b89247773"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amass_searches",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "domain", sa.String(length=255), nullable=False, comment="Domain that was scanned"
        ),
        sa.Column(
            "brute_force",
            sa.Boolean(),
            nullable=False,
            comment="Whether wordlist brute-forcing was enabled for this scan",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="running, completed, cancelled, or failed",
        ),
        sa.Column("error", sa.Text(), nullable=True, comment="Error detail if status is failed"),
        sa.Column(
            "hosts_found",
            sa.Integer(),
            nullable=False,
            comment="Distinct hosts found for this domain at scan completion",
        ),
        sa.Column(
            "searched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When the search ran",
        ),
        sa.Column(
            "result",
            sa.JSON(),
            nullable=True,
            comment=(
                "Full {'hosts': [...]} result - accumulates across every scan of a domain, "
                "see AmassSearch model / docs/architecture/amass.md"
            ),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_amass_searches_domain"), "amass_searches", ["domain"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_amass_searches_domain"), table_name="amass_searches")
    op.drop_table("amass_searches")
    # ### end Alembic commands ###
