"""add phone search tables

Revision ID: 8d9be91ec8d9
Revises: 5ea952ba68b5
Create Date: 2026-09-29 04:04:30.258871

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d9be91ec8d9"
down_revision: str | None = "5ea952ba68b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phone_search_config",
        sa.Column("id", sa.Integer(), nullable=False, comment="Singleton row id, always 1"),
        sa.Column(
            "timeout_seconds",
            sa.Integer(),
            nullable=False,
            comment="Per-provider check timeout, in seconds",
        ),
        sa.Column(
            "proxy_url",
            sa.String(length=500),
            nullable=True,
            comment="Optional HTTP(S) proxy URL for provider checks",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "phone_searches",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "phone_number",
            sa.String(length=20),
            nullable=False,
            comment="E.164 phone number searched across providers",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="running, completed, cancelled, or failed",
        ),
        sa.Column(
            "total_providers_checked",
            sa.Integer(),
            nullable=False,
            comment="Providers checked so far",
        ),
        sa.Column(
            "found_count",
            sa.Integer(),
            nullable=False,
            comment="Providers where the number was found registered",
        ),
        sa.Column(
            "error_message",
            sa.String(length=1000),
            nullable=True,
            comment="Error detail if status is failed",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When the search run started",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the search run finished, if it has",
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'cancelled', 'failed')",
            name="ck_phone_searches_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_phone_searches_phone_number"), "phone_searches", ["phone_number"], unique=False
    )
    op.create_index(op.f("ix_phone_searches_status"), "phone_searches", ["status"], unique=False)
    op.create_table(
        "phone_search_results",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column("search_id", sa.Integer(), nullable=False, comment="Owning PhoneSearch.id"),
        sa.Column(
            "provider_name",
            sa.String(length=100),
            nullable=False,
            comment="Provider/service where the number was found registered",
        ),
        sa.Column(
            "extra",
            sa.JSON(),
            nullable=True,
            comment="Provider-specific extras not worth their own columns",
        ),
        sa.ForeignKeyConstraint(["search_id"], ["phone_searches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_phone_search_results_search_id"),
        "phone_search_results",
        ["search_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_phone_search_results_search_id"), table_name="phone_search_results")
    op.drop_table("phone_search_results")
    op.drop_index(op.f("ix_phone_searches_status"), table_name="phone_searches")
    op.drop_index(op.f("ix_phone_searches_phone_number"), table_name="phone_searches")
    op.drop_table("phone_searches")
    op.drop_table("phone_search_config")
    # ### end Alembic commands ###
