"""initial schema

Revision ID: df83f89370e9
Revises:
Create Date: 2026-07-25 14:50:02.530758

Squashes the 22 migrations that previously accumulated here (see git history
if you need the incremental steps - each one earned its keep at the time, but
nothing had shipped to a real installation yet, so replaying them one by one
bought nothing). This single revision creates the schema exactly as
`Base.metadata` declares it today; `alembic upgrade head` on an empty
database now really does build the schema - no separate `create_all()`/
`stamp head` dance needed for a fresh install (see docker-entrypoint.py).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.core.settings.api_keys.models.api_keys_settings_models

# revision identifiers, used by Alembic.
revision: str = "df83f89370e9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_settings",
        sa.Column("id", sa.Integer(), nullable=False, comment="Singleton row id, always 1"),
        sa.Column(
            "default_model",
            sa.String(length=80),
            nullable=False,
            comment="Fallback LLM model id used when a feature has no override set",
        ),
        sa.Column(
            "newsfeed_analysis_model",
            sa.String(length=80),
            nullable=True,
            comment="LLM model override for newsfeed article analysis; null = use default_model",
        ),
        sa.Column(
            "newsfeed_report_model",
            sa.String(length=80),
            nullable=True,
            comment="LLM model override for newsfeed report generation; null = use default_model",
        ),
        sa.Column(
            "email_analyzer_model",
            sa.String(length=80),
            nullable=True,
            comment="LLM model override for email search analysis; null = use default_model",
        ),
        sa.Column(
            "llm_templates_model",
            sa.String(length=80),
            nullable=True,
            comment="LLM model override for AI template execution; null = use default_model",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "module",
            sa.String(length=100),
            nullable=False,
            comment="Feature/module that raised this alert",
        ),
        sa.Column("title", sa.String(length=200), nullable=False, comment="Short alert headline"),
        sa.Column(
            "message", sa.String(length=1000), nullable=False, comment="Full alert body text"
        ),
        sa.Column(
            "read",
            sa.Boolean(),
            nullable=False,
            comment="Whether the user has dismissed/read this alert",
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When the alert was raised",
        ),
        sa.Column(
            "timestamp_read",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the alert was marked as read, if it has been",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_module"), "alerts", ["module"], unique=False)
    op.create_index(op.f("ix_alerts_read"), "alerts", ["read"], unique=False)
    op.create_table(
        "apikeys",
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Unique name of the API key provider",
        ),
        sa.Column(
            "key",
            app.core.settings.api_keys.models.api_keys_settings_models.EncryptedString(),
            nullable=False,
            comment="The API key value (encrypted at rest)",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Whether the key is active for use"
        ),
        sa.Column(
            "bulk_ioc_lookup",
            sa.Boolean(),
            nullable=False,
            comment="Whether bulk lookup is enabled",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was last updated",
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "blacklisted_addresses",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "address",
            sa.String(length=128),
            nullable=False,
            comment="Blockchain address or IOC value",
        ),
        sa.Column(
            "source",
            sa.String(length=20),
            nullable=False,
            comment="Feed this entry came from: 'OFAC' or 'SCAMSNIFFER'",
        ),
        sa.Column(
            "chain",
            sa.String(length=20),
            nullable=True,
            comment="Blockchain the address belongs to, if known",
        ),
        sa.Column(
            "label",
            sa.String(length=255),
            nullable=True,
            comment="Short human-readable label for the entry",
        ),
        sa.Column(
            "entity_name",
            sa.String(length=255),
            nullable=True,
            comment="Sanctioned/flagged entity name, if known",
        ),
        sa.Column("details", sa.JSON(), nullable=True, comment="Raw source-specific feed record"),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether the entry is still present in the source feed",
        ),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this entry was first ingested",
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this entry was last seen in a feed refresh",
        ),
        sa.CheckConstraint(
            "source IN ('OFAC', 'SCAMSNIFFER')", name="ck_blacklisted_addresses_source"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address", "source", name="uq_blacklist_address_source"),
    )
    op.create_index(
        op.f("ix_blacklisted_addresses_address"), "blacklisted_addresses", ["address"], unique=False
    )
    op.create_index(
        op.f("ix_blacklisted_addresses_source"), "blacklisted_addresses", ["source"], unique=False
    )
    op.create_table(
        "cti_profile_settings",
        sa.Column("id", sa.Integer(), nullable=False, comment="Singleton row id, always 1"),
        sa.Column(
            "settings_data",
            sa.JSON(),
            nullable=False,
            comment="Free-form CTI profile config (sectors, regions, keywords, etc.)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "email_search_config",
        sa.Column("id", sa.Integer(), nullable=False, comment="Singleton row id, always 1"),
        sa.Column(
            "timeout_seconds",
            sa.Integer(),
            nullable=False,
            comment="Per-provider check timeout, in seconds",
        ),
        sa.Column(
            "max_concurrency",
            sa.Integer(),
            nullable=False,
            comment="Max number of providers checked in parallel",
        ),
        sa.Column(
            "proxy_url",
            sa.String(length=500),
            nullable=True,
            comment="Optional HTTP(S) proxy URL for provider checks",
        ),
        sa.Column(
            "use_tor", sa.Boolean(), nullable=False, comment="Whether to route checks through Tor"
        ),
        sa.Column(
            "enable_smtp_checks",
            sa.Boolean(),
            nullable=False,
            comment="Whether to run SMTP-based mailbox existence checks",
        ),
        sa.Column(
            "enable_headless_checks",
            sa.Boolean(),
            nullable=False,
            comment="Whether to run headless-browser-based provider checks",
        ),
        sa.Column(
            "latest_pypi_version",
            sa.String(length=50),
            nullable=True,
            comment="Latest version seen on PyPI for the vendored tool, cached from the last check",
        ),
        sa.Column(
            "pypi_checked_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When latest_pypi_version was last refreshed",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "general_settings",
        sa.Column("id", sa.Integer(), nullable=False, comment="Singleton row id, always 1"),
        sa.Column(
            "darkmode", sa.Boolean(), nullable=False, comment="Whether the UI theme is dark mode"
        ),
        sa.Column(
            "language",
            sa.String(length=5),
            nullable=False,
            comment="UI language code (e.g. 'en', 'ru')",
        ),
        sa.Column(
            "auto_open_on_single_match",
            sa.Boolean(),
            nullable=False,
            comment="Whether to auto-open the result when a search returns exactly one match",
        ),
        sa.Column(
            "start_screen",
            sa.String(length=20),
            nullable=False,
            comment="Which screen the app opens on startup",
        ),
        sa.Column(
            "always_tiles",
            sa.Boolean(),
            nullable=False,
            comment="Whether to always use tile layout instead of tabs",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "git_recon_searches",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "mode",
            sa.String(length=20),
            nullable=False,
            comment="gitcolombo scan mode (e.g. 'user', 'org', 'repo')",
        ),
        sa.Column(
            "target",
            sa.String(length=300),
            nullable=False,
            comment="GitHub user/org/repo that was scanned",
        ),
        sa.Column("status", sa.String(length=20), nullable=False, comment="completed or failed"),
        sa.Column("error", sa.Text(), nullable=True, comment="Error detail if status is failed"),
        sa.Column(
            "repos_scanned",
            sa.Integer(),
            nullable=False,
            comment="Repositories successfully scanned",
        ),
        sa.Column(
            "repos_failed", sa.Integer(), nullable=False, comment="Repositories that failed to scan"
        ),
        sa.Column(
            "persons_found", sa.Integer(), nullable=False, comment="Distinct identities correlated"
        ),
        sa.Column(
            "searched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When the search ran",
        ),
        sa.Column(
            "result",
            sa.JSON(),
            nullable=True,
            comment=(
                "Full gitcolombo result blob - no normalized result table, see "
                "database-schema-audit.md #12"
            ),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_git_recon_searches_target"), "git_recon_searches", ["target"], unique=False
    )
    op.create_table(
        "keywords",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "keyword",
            sa.String(length=100),
            nullable=False,
            comment="Watched keyword, lowercased/stripped by validate_keyword",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_keywords_keyword"), "keywords", ["keyword"], unique=True)
    op.create_table(
        "maigret_searches",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column("username", sa.String(length=100), nullable=False, comment="Username searched"),
        sa.Column(
            "source",
            sa.String(length=30),
            server_default="maigret",
            nullable=False,
            comment="Which tool produced this run: 'maigret' or 'social_analyzer'",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="running, completed, cancelled, or failed",
        ),
        sa.Column(
            "total_sites_checked", sa.Integer(), nullable=False, comment="Sites checked so far"
        ),
        sa.Column(
            "found_count",
            sa.Integer(),
            nullable=False,
            comment="Sites where the username was claimed/found",
        ),
        sa.Column(
            "error_message",
            sa.String(length=1000),
            nullable=True,
            comment="Error detail if status is failed",
        ),
        sa.Column(
            "tags",
            sa.JSON(),
            nullable=True,
            comment="Maigret category tags matched for this username",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When the search run started",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the search run finished, if it has",
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'cancelled', 'failed')",
            name="ck_maigret_searches_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_maigret_searches_source"), "maigret_searches", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_maigret_searches_status"), "maigret_searches", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_maigret_searches_username"), "maigret_searches", ["username"], unique=False
    )
    op.create_table(
        "mail_searches",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "username",
            sa.String(length=100),
            nullable=False,
            comment="Username/email searched across providers",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="running, completed, cancelled, or failed",
        ),
        sa.Column(
            "total_providers_checked",
            sa.Integer(),
            nullable=False,
            comment="Providers checked so far",
        ),
        sa.Column(
            "found_count",
            sa.Integer(),
            nullable=False,
            comment="Providers where a registered account was found",
        ),
        sa.Column(
            "error_message",
            sa.String(length=1000),
            nullable=True,
            comment="Error detail if status is failed",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When the search run started",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the search run finished, if it has",
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'cancelled', 'failed')",
            name="ck_mail_searches_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mail_searches_status"), "mail_searches", ["status"], unique=False)
    op.create_index(op.f("ix_mail_searches_username"), "mail_searches", ["username"], unique=False)
    op.create_table(
        "module_settings",
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment=(
                "Module identifier; 100 matches MODULE_NAME_MAX_LENGTH in "
                "config/default_settings.py"
            ),
        ),
        sa.Column(
            "enabled",
            sa.Boolean(),
            nullable=False,
            comment="Whether this module is enabled and visible in the UI",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was last updated",
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "newsfeed_config",
        sa.Column("id", sa.Integer(), nullable=False, comment="Singleton row id, always 1"),
        sa.Column(
            "retention_days",
            sa.Integer(),
            nullable=False,
            comment="Days to keep articles before pruning; 0 = keep forever",
        ),
        sa.Column(
            "background_fetch_enabled",
            sa.Boolean(),
            nullable=False,
            comment="Whether the scheduler job fetches feeds automatically",
        ),
        sa.Column(
            "fetch_interval_minutes",
            sa.Integer(),
            nullable=False,
            comment="Minutes between scheduled feed fetches",
        ),
        sa.Column(
            "last_fetch_timestamp",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the background fetch job last ran, across all feeds",
        ),
        sa.Column(
            "keyword_matching_enabled",
            sa.Boolean(),
            nullable=False,
            comment="Whether articles are matched against the configured keyword list",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "newsfeed_settings",
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Unique feed name, natural key"
        ),
        sa.Column("url", sa.String(length=2048), nullable=False, comment="RSS/Atom feed URL"),
        sa.Column(
            "icon",
            sa.String(length=36),
            nullable=False,
            comment=(
                "'default.png' or <uuid4().hex>.png written by favicon_downloader.py - "
                "36 chars covers both"
            ),
        ),
        sa.Column(
            "icon_id",
            sa.String(),
            nullable=False,
            comment="Cache-busting id appended to the icon URL on the frontend",
        ),
        sa.Column(
            "enabled", sa.Boolean(), nullable=False, comment="Whether this feed is actively fetched"
        ),
        sa.Column(
            "deleted",
            sa.Boolean(),
            nullable=False,
            comment="Soft-delete flag; kept to avoid orphaning already-stored news_articles rows",
        ),
        sa.Column(
            "last_fetched_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When this feed was last polled, regardless of outcome",
        ),
        sa.Column(
            "last_success_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When this feed was last polled successfully",
        ),
        sa.Column(
            "last_error",
            sa.String(length=500),
            nullable=True,
            comment="Error message from the last failed fetch, if any",
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "reddit_searches",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "username", sa.String(length=100), nullable=False, comment="Reddit username searched"
        ),
        sa.Column(
            "subreddit_filter",
            sa.String(length=100),
            nullable=True,
            comment="Optional single subreddit to restrict to",
        ),
        sa.Column(
            "date_from",
            sa.Integer(),
            nullable=True,
            comment="unix timestamp, not DateTime - Arctic Shift/PullPush take unix cursors",
        ),
        sa.Column(
            "date_to",
            sa.Integer(),
            nullable=True,
            comment="unix timestamp, not DateTime - Arctic Shift/PullPush take unix cursors",
        ),
        sa.Column(
            "include_nsfw",
            sa.Boolean(),
            nullable=False,
            comment="Whether NSFW-flagged content is included",
        ),
        sa.Column(
            "searched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When the search ran",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reddit_searches_username"), "reddit_searches", ["username"], unique=False
    )
    op.create_table(
        "single_lookup_searches",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "ioc",
            sa.String(length=2000),
            nullable=False,
            comment="The IOC value that was looked up",
        ),
        sa.Column(
            "ioc_type",
            sa.String(length=20),
            nullable=False,
            comment="IOC type (e.g. ip, domain, hash, address)",
        ),
        sa.Column(
            "searched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When the lookup ran",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_single_lookup_searches_ioc"), "single_lookup_searches", ["ioc"], unique=False
    )
    op.create_index(
        op.f("ix_single_lookup_searches_ioc_type"),
        "single_lookup_searches",
        ["ioc_type"],
        unique=False,
    )
    op.create_table(
        "social_analyzer_config",
        sa.Column("id", sa.Integer(), nullable=False, comment="Singleton row id, always 1"),
        sa.Column(
            "timeout_seconds",
            sa.Integer(),
            nullable=False,
            comment="Per-site check timeout, in seconds (0 = no timeout)",
        ),
        sa.Column(
            "top_sites_count",
            sa.Integer(),
            nullable=False,
            comment="Max number of top sites to scan (0 = scan all sites)",
        ),
        sa.Column(
            "latest_pypi_version",
            sa.String(length=50),
            nullable=True,
            comment="Latest version seen on PyPI for the vendored tool, cached from the last check",
        ),
        sa.Column(
            "pypi_checked_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When latest_pypi_version was last refreshed",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "template_categories",
        sa.Column(
            "id", sa.String(length=36), nullable=False, comment="Unique identifier for the category"
        ),
        sa.Column(
            "name", sa.String(length=100), nullable=False, comment="Display name of the category"
        ),
        sa.Column(
            "order_number",
            sa.Integer(),
            nullable=False,
            comment="Display order for category listing",
        ),
        sa.Column(
            "is_system",
            sa.Boolean(),
            nullable=False,
            comment="Whether this is a system category that cannot be deleted or renamed",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trends_blacklist",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "value",
            sa.String(length=255),
            nullable=False,
            comment="Blacklisted word or IOC value, lowercased",
        ),
        sa.Column("type", sa.String(length=10), nullable=False, comment="'word' or 'ioc'"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this entry was added",
        ),
        sa.CheckConstraint("type IN ('word', 'ioc')", name="ck_trends_blacklist_type"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("value", "type", name="uq_blacklist_value_type"),
    )
    op.create_index(op.f("ix_trends_blacklist_value"), "trends_blacklist", ["value"], unique=False)
    op.create_table(
        "username_search_config",
        sa.Column("id", sa.Integer(), nullable=False, comment="Singleton row id, always 1"),
        sa.Column(
            "timeout_seconds",
            sa.Integer(),
            nullable=False,
            comment="Per-site check timeout, in seconds",
        ),
        sa.Column(
            "max_concurrency",
            sa.Integer(),
            nullable=False,
            comment="Max number of sites checked in parallel",
        ),
        sa.Column(
            "top_sites_count",
            sa.Integer(),
            nullable=False,
            comment="Max number of top sites to scan (0 = scan all sites)",
        ),
        sa.Column(
            "proxy_url",
            sa.String(length=500),
            nullable=True,
            comment="Optional HTTP(S) proxy URL for site checks",
        ),
        sa.Column(
            "auto_update_db_enabled",
            sa.Boolean(),
            nullable=False,
            comment="Whether Maigret's site database is refreshed automatically on a schedule",
        ),
        sa.Column(
            "auto_update_interval_hours",
            sa.Integer(),
            nullable=False,
            comment="Hours between automatic site-database refreshes",
        ),
        sa.Column(
            "db_last_updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the Maigret site database was last refreshed",
        ),
        sa.Column(
            "db_site_count",
            sa.Integer(),
            nullable=False,
            comment="Number of sites in the current Maigret site database",
        ),
        sa.Column(
            "latest_pypi_version",
            sa.String(length=50),
            nullable=True,
            comment="Latest version seen on PyPI for the vendored tool, cached from the last check",
        ),
        sa.Column(
            "pypi_checked_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When latest_pypi_version was last refreshed",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ai_templates",
        sa.Column(
            "id", sa.String(length=36), nullable=False, comment="Unique identifier for the template"
        ),
        sa.Column(
            "title", sa.String(length=200), nullable=False, comment="Human-readable template title"
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Detailed description of the template's purpose",
        ),
        sa.Column(
            "example_input_output",
            sa.Text(),
            nullable=True,
            comment="Example showing expected input and output format",
        ),
        sa.Column(
            "ai_agent_role",
            sa.Text(),
            nullable=False,
            comment="System prompt defining the AI agent's role and persona",
        ),
        sa.Column(
            "ai_agent_task",
            sa.Text(),
            nullable=False,
            comment="Task prompt with instructions for the AI agent",
        ),
        sa.Column(
            "payload_fields",
            sa.JSON(),
            nullable=False,
            comment="JSON array defining required input fields for the template",
        ),
        sa.Column(
            "static_contexts",
            sa.JSON(),
            nullable=True,
            comment="JSON array of static context information to include in prompts",
        ),
        sa.Column(
            "web_contexts",
            sa.JSON(),
            nullable=True,
            comment="JSON array of web URLs to fetch and include as context",
        ),
        sa.Column(
            "is_public",
            sa.Boolean(),
            nullable=False,
            comment="Whether the template is publicly accessible",
        ),
        sa.Column(
            "user_id",
            sa.String(length=100),
            nullable=True,
            comment="ID of the user who created the template",
        ),
        sa.Column(
            "order_number",
            sa.Integer(),
            nullable=True,
            comment="Display order for template listing",
        ),
        sa.Column(
            "temperature",
            sa.Float(),
            nullable=True,
            comment="LLM temperature setting (0.0-1.0) for response randomness",
        ),
        sa.Column(
            "model",
            sa.String(length=100),
            nullable=True,
            comment=(
                "Default LLM model to use for template execution (null = use configured default)"
            ),
        ),
        sa.Column(
            "category_id",
            sa.String(length=36),
            nullable=True,
            comment="Category this template belongs to",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="When this row was last updated",
        ),
        sa.ForeignKeyConstraint(["category_id"], ["template_categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "maigret_site_results",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column("search_id", sa.Integer(), nullable=False, comment="Owning MaigretSearch.id"),
        sa.Column(
            "site_name",
            sa.String(length=200),
            nullable=False,
            comment="Site where the username was claimed/found",
        ),
        sa.Column(
            "url_user",
            sa.String(length=2000),
            nullable=False,
            comment="Direct URL to the found profile",
        ),
        sa.Column(
            "http_status",
            sa.Integer(),
            nullable=True,
            comment="HTTP status code returned by the site check",
        ),
        sa.Column(
            "extra",
            sa.JSON(),
            nullable=True,
            comment=(
                "Source-specific extras not worth their own columns (e.g. "
                "social-analyzer's match rate/title)"
            ),
        ),
        sa.ForeignKeyConstraint(["search_id"], ["maigret_searches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_maigret_site_results_search_id"),
        "maigret_site_results",
        ["search_id"],
        unique=False,
    )
    op.create_table(
        "mail_search_results",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column("search_id", sa.Integer(), nullable=False, comment="Owning MailSearch.id"),
        sa.Column(
            "provider_name",
            sa.String(length=200),
            nullable=False,
            comment="Provider/service where the account was found",
        ),
        sa.Column(
            "emails",
            sa.JSON(),
            nullable=False,
            comment="Email address(es) found registered with this provider",
        ),
        sa.Column(
            "extra",
            sa.JSON(),
            nullable=True,
            comment="Provider-specific extras not worth their own columns",
        ),
        sa.ForeignKeyConstraint(["search_id"], ["mail_searches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mail_search_results_search_id"), "mail_search_results", ["search_id"], unique=False
    )
    op.create_table(
        "news_articles",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "feedname",
            sa.String(length=255),
            nullable=False,
            comment="Owning feed's name (newsfeed_settings.name)",
        ),
        sa.Column(
            "icon",
            sa.String(length=36),
            nullable=False,
            comment="Copy of the owning feed's icon filename at fetch time",
        ),
        sa.Column("title", sa.String(length=500), nullable=False, comment="Article title"),
        sa.Column(
            "summary",
            sa.Text(),
            nullable=False,
            comment=(
                "RSS description/summary field - no length cap in "
                "feed_processing_service.py, some feeds put substantial content here, "
                "so Text rather than a guessed VARCHAR(N)"
            ),
        ),
        sa.Column("full_text", sa.Text(), nullable=True, comment="Full article body, if fetched"),
        sa.Column(
            "date",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Publication date as reported by the feed",
        ),
        sa.Column(
            "link", sa.String(length=2048), nullable=False, comment="Article URL, deduplication key"
        ),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When this article was ingested by Corvid",
        ),
        sa.Column(
            "matches",
            sa.JSON(),
            nullable=True,
            comment="Keyword-matching hits found in this article",
        ),
        sa.Column(
            "iocs", sa.JSON(), nullable=True, comment="IOCs extracted from the article, by type"
        ),
        sa.Column(
            "relevant_iocs",
            sa.JSON(),
            nullable=True,
            comment="Subset of iocs judged relevant to the configured CTI profile",
        ),
        sa.Column(
            "analysis_result",
            sa.Text(),
            nullable=True,
            comment="LLM-generated analysis of the article",
        ),
        sa.Column(
            "mitre_attack",
            sa.Text(),
            nullable=True,
            comment="LLM-extracted MITRE ATT&CK technique mapping",
        ),
        sa.Column("note", sa.Text(), nullable=True, comment="User-entered free-text note"),
        sa.Column("tlp", sa.String(), nullable=False, comment="Traffic Light Protocol label"),
        sa.Column(
            "read",
            sa.Boolean(),
            nullable=False,
            comment="Whether the user has marked this article as read",
        ),
        sa.ForeignKeyConstraint(["feedname"], ["newsfeed_settings.name"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_news_articles_date"), "news_articles", ["date"], unique=False)
    op.create_index(op.f("ix_news_articles_feedname"), "news_articles", ["feedname"], unique=False)
    op.create_index(op.f("ix_news_articles_link"), "news_articles", ["link"], unique=True)
    op.create_table(
        "reddit_search_results",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column("search_id", sa.Integer(), nullable=False, comment="Owning RedditSearch.id"),
        sa.Column("kind", sa.String(length=10), nullable=False, comment="'post' or 'comment'"),
        sa.Column(
            "reddit_id",
            sa.String(length=20),
            nullable=False,
            comment="Reddit's own id for this post/comment (stable across runs)",
        ),
        sa.Column(
            "subreddit",
            sa.String(length=100),
            nullable=False,
            comment="Subreddit the post/comment was made in",
        ),
        sa.Column("title", sa.Text(), nullable=True, comment="Post title (null for comments)"),
        sa.Column("body", sa.Text(), nullable=True, comment="Post selftext or comment body"),
        sa.Column(
            "score", sa.Integer(), nullable=False, comment="Reddit score/upvotes at time of fetch"
        ),
        sa.Column(
            "num_comments",
            sa.Integer(),
            nullable=True,
            comment="Comment count at time of fetch (posts only)",
        ),
        sa.Column(
            "permalink",
            sa.String(length=500),
            nullable=False,
            comment="Relative Reddit URL to the post/comment",
        ),
        sa.Column(
            "created_utc",
            sa.Integer(),
            nullable=False,
            comment="unix timestamp, not DateTime - as returned by Arctic Shift/PullPush",
        ),
        sa.Column(
            "over_18",
            sa.Boolean(),
            nullable=False,
            comment="Whether the post/comment is NSFW-flagged",
        ),
        sa.Column(
            "removed",
            sa.Boolean(),
            nullable=False,
            comment="Whether the post/comment was removed by mods",
        ),
        sa.Column(
            "deleted",
            sa.Boolean(),
            nullable=False,
            comment="Whether the author deleted the post/comment",
        ),
        sa.Column(
            "extra",
            sa.JSON(),
            nullable=True,
            comment="Source-specific extras not worth their own columns",
        ),
        sa.ForeignKeyConstraint(["search_id"], ["reddit_searches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "search_id", "kind", "reddit_id", name="uq_reddit_result_search_kind_id"
        ),
    )
    op.create_index(
        op.f("ix_reddit_search_results_created_utc"),
        "reddit_search_results",
        ["created_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reddit_search_results_search_id"),
        "reddit_search_results",
        ["search_id"],
        unique=False,
    )
    op.create_table(
        "single_lookup_results",
        sa.Column("id", sa.Integer(), nullable=False, comment="Surrogate primary key"),
        sa.Column(
            "search_id", sa.Integer(), nullable=False, comment="Owning SingleLookupSearch.id"
        ),
        sa.Column(
            "service_key",
            sa.String(length=100),
            nullable=False,
            comment="Internal identifier of the queried service",
        ),
        sa.Column(
            "service_name",
            sa.String(length=200),
            nullable=False,
            comment="Human-readable name of the queried service",
        ),
        sa.Column(
            "status", sa.String(length=20), nullable=False, comment="found, not_found, or error"
        ),
        sa.Column(
            "summary",
            sa.String(length=500),
            nullable=False,
            comment="Short human-readable summary of the result",
        ),
        sa.Column(
            "tlp",
            sa.String(length=20),
            nullable=False,
            comment="Traffic Light Protocol label for this result",
        ),
        sa.Column("data", sa.JSON(), nullable=True, comment="Full raw response from the service"),
        sa.ForeignKeyConstraint(["search_id"], ["single_lookup_searches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_single_lookup_results_search_id"),
        "single_lookup_results",
        ["search_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_single_lookup_results_search_id"), table_name="single_lookup_results")
    op.drop_table("single_lookup_results")
    op.drop_index(op.f("ix_reddit_search_results_search_id"), table_name="reddit_search_results")
    op.drop_index(op.f("ix_reddit_search_results_created_utc"), table_name="reddit_search_results")
    op.drop_table("reddit_search_results")
    op.drop_index(op.f("ix_news_articles_link"), table_name="news_articles")
    op.drop_index(op.f("ix_news_articles_feedname"), table_name="news_articles")
    op.drop_index(op.f("ix_news_articles_date"), table_name="news_articles")
    op.drop_table("news_articles")
    op.drop_index(op.f("ix_mail_search_results_search_id"), table_name="mail_search_results")
    op.drop_table("mail_search_results")
    op.drop_index(op.f("ix_maigret_site_results_search_id"), table_name="maigret_site_results")
    op.drop_table("maigret_site_results")
    op.drop_table("ai_templates")
    op.drop_table("username_search_config")
    op.drop_index(op.f("ix_trends_blacklist_value"), table_name="trends_blacklist")
    op.drop_table("trends_blacklist")
    op.drop_table("template_categories")
    op.drop_table("social_analyzer_config")
    op.drop_index(op.f("ix_single_lookup_searches_ioc_type"), table_name="single_lookup_searches")
    op.drop_index(op.f("ix_single_lookup_searches_ioc"), table_name="single_lookup_searches")
    op.drop_table("single_lookup_searches")
    op.drop_index(op.f("ix_reddit_searches_username"), table_name="reddit_searches")
    op.drop_table("reddit_searches")
    op.drop_table("newsfeed_settings")
    op.drop_table("newsfeed_config")
    op.drop_table("module_settings")
    op.drop_index(op.f("ix_mail_searches_username"), table_name="mail_searches")
    op.drop_index(op.f("ix_mail_searches_status"), table_name="mail_searches")
    op.drop_table("mail_searches")
    op.drop_index(op.f("ix_maigret_searches_username"), table_name="maigret_searches")
    op.drop_index(op.f("ix_maigret_searches_status"), table_name="maigret_searches")
    op.drop_index(op.f("ix_maigret_searches_source"), table_name="maigret_searches")
    op.drop_table("maigret_searches")
    op.drop_index(op.f("ix_keywords_keyword"), table_name="keywords")
    op.drop_table("keywords")
    op.drop_index(op.f("ix_git_recon_searches_target"), table_name="git_recon_searches")
    op.drop_table("git_recon_searches")
    op.drop_table("general_settings")
    op.drop_table("email_search_config")
    op.drop_table("cti_profile_settings")
    op.drop_index(op.f("ix_blacklisted_addresses_source"), table_name="blacklisted_addresses")
    op.drop_index(op.f("ix_blacklisted_addresses_address"), table_name="blacklisted_addresses")
    op.drop_table("blacklisted_addresses")
    op.drop_table("apikeys")
    op.drop_index(op.f("ix_alerts_read"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_module"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_table("ai_settings")
    # ### end Alembic commands ###
