"""add image_geolocation_model to ai_settings

Revision ID: e541fd2b2817
Revises: df83f89370e9
Create Date: 2026-07-30 15:45:27.036419

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e541fd2b2817"
down_revision: str | None = "df83f89370e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_settings",
        sa.Column(
            "image_geolocation_model",
            sa.String(length=80),
            nullable=True,
            comment="LLM model override for AI photo geolocation; null = use default_model",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_settings", "image_geolocation_model")
    # ### end Alembic commands ###
